version: '2'
services:
    jhgateway-cassandra:
        container_name: jhgateway-cassandra
        image: cassandra:2.2.5
        # volumes:
        #     - ~/volumes/jhipster/jhgateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    jhgateway-cassandra-node:
        image: cassandra:2.2.5
        links:
            - jhgateway-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    jhgateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhgateway-cassandra-migration
        links:
            - jhgateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
